version: 2
updates:
    - package-ecosystem: maven
      directory: "/"
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: com.tngtech.archunit:archunit-junit4
            versions:
                - 0.15.0
                - 0.16.0
                - 0.17.0
          - dependency-name: com.puppycrawl.tools:checkstyle
            versions:
                - "8.41"
          - dependency-name: com.github.spotbugs:spotbugs-maven-plugin
            versions:
                - 4.2.0
          - dependency-name: org.apache.maven.plugins:maven-checkstyle-plugin
            versions:
                - 3.1.2
