language: java

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "mivek-github"
    token:
      secure: $SONARCLOUD_TOKEN

jdk: oraclejdk8

before_install:
  # Retrieve keys only if build is not on a pull request
  - bash scripts/before_install.sh

install:
  - mvn compile test-compile
  
script:
  # If the branch is master then the deploy goal is used otherwise the maven install is used
  - bash scripts/script.sh

before_deploy:
  - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - bash scripts/before_deploy.sh ${VERSION}

deploy:
  provider: releases
  file: target/metarParser-${VERSION}.jar
  api_key:
    secure: $GITHUB_OATH
  skip_cleanup: true
  draft: true
  name: ${VERSION}
  on:
    branch: master
